

CONFIG_ZMK_DEVTOOL=y
CONFIG_ZMK_DEVTOOL_STUDIO_RPC=y

CONFIG_ZMK_DEVTOOL_KEY_INJECTION=y
CONFIG_ZMK_DEVTOOL_EVENT_TAP=y
CONFIG_ZMK_DEVTOOL_LOG_CAPTURE=y
CONFIG_ZMK_DEVTOOL_STACK_USAGE=y

# https://github.com/cormoran/zmk-feature-zephyr-setting-expose
CONFIG_ZMK_SETTING_EXPOSE=y
# CONFIG_ZMK_STUDIO_RPC_CUSTOM_SUBSYSTEM_REQUEST_PAYLOAD_MAX_BYTES=140 # already configured as larger value

# https://github.com/cormoran/zmk-feature-studio-rpc-perf
CONFIG_ZMK_STUDIO_RPC_PERF=y
CONFIG_ZMK_STUDIO_RPC_PERF_HANDLER=y
CONFIG_ZMK_STUDIO_RPC_PERF_SPLIT_RPC_RELAY=y
# CONFIG_ZMK_SPLIT_RELAY_EVENT_DATA_LEN=256 # for larger perf

# https://github.com/cormoran/zmk-feature-kscan-diagnostics
CONFIG_ZMK_KSCAN_DIAGNOSTICS=y
CONFIG_ZMK_KSCAN_DIAGNOSTICS_STUDIO_RPC=y


